[package]
name = "generator"
version = "0.1.0"
authors = ["duck84 <mmcgrath@pdx.edu>", "jzcs <jesszhu@pdx.edu>"]

[dependencies]
rand = "0.5.4"
clap = "2.32.0"
regex = "1.0.2"
Inflector = "*"
colored = "1.6.1"
